# Generated by Django 5.1.15 on 2026-06-15 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recruitments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "desired_lane",
                    models.CharField(max_length=16, verbose_name="希望レーン"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="コメント")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "応募中"),
                            ("approved", "承認"),
                            ("rejected", "見送り"),
                            ("withdrawn", "取り下げ"),
                            ("declined", "辞退"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="状態",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="応募日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recruitment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="recruitments.recruitment",
                    ),
                ),
            ],
            options={
                "verbose_name": "応募",
                "verbose_name_plural": "応募",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("recruitment", "applicant"), name="unique_application"
                    )
                ],
            },
        ),
    ]
