# Generated by Django 5.1.15 on 2026-06-15 05:57

import accounts.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="SanctionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discord_id",
                    models.CharField(
                        db_index=True, max_length=32, verbose_name="Discord ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("warning", "警告"), ("suspension", "凍結")],
                        max_length=16,
                        verbose_name="種別",
                    ),
                ),
                ("reason", models.TextField(verbose_name="理由")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="発行日時"),
                ),
            ],
            options={
                "verbose_name": "制裁記録",
                "verbose_name_plural": "制裁記録",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "discord_id",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Discord ID"
                    ),
                ),
                (
                    "discord_created_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Snowflake から算出(F-UNIQ-07)",
                        null=True,
                        verbose_name="Discord アカウント作成日時",
                    ),
                ),
                (
                    "discord_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Discord 名"
                    ),
                ),
                ("avatar_url", models.URLField(blank=True, verbose_name="アバターURL")),
                (
                    "riot_game_name",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Riot ゲーム名"
                    ),
                ),
                (
                    "riot_tagline",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="Riot タグライン"
                    ),
                ),
                (
                    "riot_puuid",
                    models.CharField(
                        blank=True,
                        help_text="一意。未連携の間は NULL(F-UNIQ-03)",
                        max_length=128,
                        null=True,
                        unique=True,
                        verbose_name="Riot PUUID",
                    ),
                ),
                (
                    "rank_solo",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="ランク(ソロ)"
                    ),
                ),
                (
                    "rank_flex",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="ランク(フレックス)"
                    ),
                ),
                (
                    "rank_fetched_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ランク取得日時"
                    ),
                ),
                (
                    "lanes",
                    models.JSONField(
                        blank=True, default=list, verbose_name="得意レーン"
                    ),
                ),
                (
                    "play_hours",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="プレイ時間帯"
                    ),
                ),
                (
                    "vc_style",
                    models.CharField(
                        choices=[
                            ("talk", "通話OK"),
                            ("listen_only", "聞き専"),
                            ("text_only", "テキストのみ"),
                            ("unset", "未設定"),
                        ],
                        default="unset",
                        max_length=16,
                        verbose_name="VC スタイル",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="自己紹介")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "アクティブ"),
                            ("warned", "警告中"),
                            ("suspended", "凍結"),
                        ],
                        default="active",
                        max_length=16,
                        verbose_name="状態",
                    ),
                ),
                (
                    "terms_agreed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="F-SAFE-06",
                        null=True,
                        verbose_name="規約同意日時",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="スタッフ権限"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="退会は論理削除(F-ACC-07)",
                        null=True,
                        verbose_name="退会日時",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "ユーザー",
                "verbose_name_plural": "ユーザー",
            },
            managers=[
                ("objects", accounts.managers.UserManager()),
            ],
        ),
    ]
