# Generated by Django 5.1.15 on 2026-06-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_completed",
            field=models.BooleanField(
                default=False,
                help_text="初回オンボーディング完了フラグ",
                verbose_name="プロフィール設定済み",
            ),
        ),
    ]
