# Generated by Django 5.1.15 on 2026-06-15 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recruitment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mode", models.CharField(max_length=64, verbose_name="ゲームモード")),
                (
                    "rank_min_idx",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="対象ランク下限"
                    ),
                ),
                (
                    "rank_max_idx",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="対象ランク上限"
                    ),
                ),
                ("start_at", models.DateTimeField(verbose_name="開始予定時刻")),
                (
                    "duration_label",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="想定プレイ時間"
                    ),
                ),
                (
                    "vc_required",
                    models.BooleanField(default=True, verbose_name="VC 必須"),
                ),
                (
                    "vc_tool",
                    models.CharField(blank=True, max_length=64, verbose_name="VC 種別"),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, verbose_name="雰囲気タグ"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="コメント")),
                (
                    "discord_invite_url",
                    models.URLField(blank=True, verbose_name="Discord 招待リンク"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "募集中"),
                            ("filled", "成立"),
                            ("closed", "締切"),
                            ("expired", "期限切れ"),
                        ],
                        default="open",
                        max_length=16,
                        verbose_name="状態",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recruitments",
                        to="games.game",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "募集",
                "verbose_name_plural": "募集",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecruitmentSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lane", models.CharField(max_length=16, verbose_name="レーン")),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="joined_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recruitment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="recruitments.recruitment",
                    ),
                ),
            ],
            options={
                "verbose_name": "募集枠",
                "verbose_name_plural": "募集枠",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="recruitment",
            index=models.Index(
                fields=["status", "start_at"], name="recruitment_status_563a74_idx"
            ),
        ),
    ]
