# Generated by Django 5.1.15 on 2026-06-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitment",
            name="is_hidden",
            field=models.BooleanField(default=False, verbose_name="運営により非公開"),
        ),
    ]
