# Generated by Django 5.1.15 on 2026-06-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitments", "0002_recruitment_is_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitment",
            name="discord_auto_invite_url",
            field=models.URLField(blank=True, verbose_name="自動発行 Discord 招待"),
        ),
        migrations.AddField(
            model_name="recruitment",
            name="discord_channel_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="後始末用に作成したカテゴリ/テキスト/VC の ID を保持",
                verbose_name="自動生成チャンネルID",
            ),
        ),
        migrations.AddField(
            model_name="recruitment",
            name="discord_cleanup_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="一時チャンネル削除予定"
            ),
        ),
        migrations.AddField(
            model_name="recruitment",
            name="discord_provisioned_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Discord 発行日時"
            ),
        ),
    ]
