# Generated by Django 5.1.15 on 2026-06-15 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("user", "ユーザー"), ("recruitment", "募集")],
                        max_length=16,
                        verbose_name="対象種別",
                    ),
                ),
                ("target_id", models.PositiveIntegerField(verbose_name="対象ID")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("harassment", "暴言・ハラスメント"),
                            ("smurf", "サブ垢・スマーフの疑い"),
                            ("no_show", "無断キャンセル"),
                            ("inappropriate", "不適切な内容"),
                            ("other", "その他"),
                        ],
                        max_length=16,
                        verbose_name="理由",
                    ),
                ),
                ("detail", models.TextField(blank=True, verbose_name="詳細")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "未対応"),
                            ("reviewing", "確認中"),
                            ("resolved", "対応済み"),
                            ("dismissed", "却下"),
                        ],
                        default="open",
                        max_length=16,
                        verbose_name="状態",
                    ),
                ),
                (
                    "handled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="対応日時"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="通報日時"),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_handled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "通報",
                "verbose_name_plural": "通報",
                "ordering": ["-created_at"],
            },
        ),
    ]
