# Generated by Django 5.1.15 on 2026-06-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="スラッグ"
                    ),
                ),
                (
                    "modes",
                    models.JSONField(
                        default=list,
                        help_text='例: ["ランク(フレックス)", "ARAM"]',
                        verbose_name="ゲームモード一覧",
                    ),
                ),
                (
                    "lanes",
                    models.JSONField(
                        default=list,
                        help_text='例: ["TOP", "JG", "MID", "ADC", "SUP", "FILL"]',
                        verbose_name="レーン/ロール一覧",
                    ),
                ),
                (
                    "rank_tiers",
                    models.JSONField(
                        default=list,
                        help_text='例: ["アイアン", "ブロンズ", ..., "チャレンジャー"]',
                        verbose_name="ランク帯一覧(低→高の順)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
            ],
            options={
                "verbose_name": "ゲーム",
                "verbose_name_plural": "ゲーム",
                "ordering": ["name"],
            },
        ),
    ]
